- hosts: localhost
  gather_facts: false
  connection: local

  tasks:

  - name: Get all VPCs
    ec2_vpc_net_info:
      region: us-east-1
      # filters:
      #   "tag:Name": ansible
    register: ansible_vpc

  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: ansible_vpc
