- name: Deploy EKS Cluster using Amazon AWS modules
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create EKS Cluster
    amazon.aws.aws_eks_cluster:
      name: eks1
      version: '1.26'
      role_arn: "arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/EKSRole"
      resources_vpc_config:
        subnet_ids:
        - subnet-0bb1c79de3EXAMPLE
        - subnet-0bb1c79de3EXAMPLE
        security_group_ids:
        - sg-0bb1c79de3EXAMPLE
      state: present

  - name: Create Node Group
    amazon.aws.aws_eks_nodegroup:
      cluster_name: my-eks-cluster
      nodegroup_name: my-node-group
      node_role_arn: "arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/EKSNodeRole"
      subnets:
      - subnet-0bb1c79de3EXAMPLE
      - subnet-0bb1c79de3EXAMPLE
      scaling_config:
        desired_size: 2
        max_size: 3
        min_size: 1
      disk_size: 20
      instance_types:
      - t3.medium
      state: present
